### ISSUE TITLE
Créer / Reprendre une partie

### ISSUE THREAD

**Issue by germainaubert** [ReineDeLaNight/Project-S3#2]
Permet de reprendre ou créer une partie.
Fait suite au clic du bouton du menu.

estimation: 1 demi-journées
réalité: 1 demi-journées

**Comment by germainaubert** [comment]
![image](https://user-images.githubusercontent.com/57391462/81192016-004da900-8fba-11ea-8e47-2841f231d107.png)

**Comment by LevWasTaken** [comment]
temps de travail effectif 1 demi journée
