### ISSUE TITLE
Création de l'objet ruche

### ISSUE THREAD

**Issue by germainaubert** [ReineDeLaNight/Project-S3#4]
Entité permettant de créer les unités nécessaires à la progression du joueur.
Miel, golden popo, unités (ouvrières, combattantes), champs, niveau de ruche, production de miel par seconde, et cout d'entretien, production - perte, stock de miel
Améliorations: ruche, production
Estimation 5 demi-journées

**Comment by Sifui** [comment]
30 minutes, restant 5 demi-journées
