### ISSUE TITLE
Création du magasin

### ISSUE THREAD

**Issue by Sifui** [ReineDeLaNight/Project-S3#9]
Création de la classe magasin ou l'utilisateur pourra acheter des abeilles

estimation: 5 demi-journées
réalité: 5 demi-journées

**Comment by germainaubert** [comment]
![achat](https://user-images.githubusercontent.com/57391462/81191863-cc728380-8fb9-11ea-9454-9058a798786f.png)

**Comment by germainaubert** [comment]
![image](https://user-images.githubusercontent.com/57391462/81283443-ee711200-905c-11ea-839d-144a9ab6789a.png)
Le bas parait coupé, car on peut scroll la page
